ARG version
FROM almalinux:${version:-9}
ENV COURSE="DevOps" \
ARG HOURS="120HRS" 
ARG TRAINER="Siva Kumar"
RUN echo "course is ${COURSE}, time is ${HOURS} and trainer is ${TRAINER}"
CMD ["sleep", "1000"]
